# Generated by Django 4.1.2 on 2022-11-10 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tag_alter_article_options_scope_article_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='basic',
            new_name='is_main',
        ),
    ]
