# Generated by Django 4.1.2 on 2022-11-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_alter_measurement_id_sensor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='measurements',
            field=models.JSONField(default='Null'),
        ),
    ]
