# Generated by Django 4.1.2 on 2022-11-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_sensor_measurements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='measurements',
        ),
    ]
