# примеры API-запросов

@baseUrl = http://localhost:8000

# получение датчиков
GET {{baseUrl}}/Sensor/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/Sensor/
Content-Type: application/json

{
  "name": "ESP32",
  "description": "Датчик на кухне перед холодильником"
}

###

# обновление датчика
PATCH {{baseUrl}}/Sensor/3/
Content-Type: application/json

{
  "description": "Перенес датчик на балкон"
}

###

# добавление измерения
POST {{baseUrl}}/Measurement/
Content-Type: application/json

{
  "id_sensor": 3,
  "temperature": 22.3
}

###

# получение информации по датчику
GET {{baseUrl}}/Measurement/3/
Content-Type: application/json
